#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_NAME="$(basename "$ROOT_DIR")"
OUTPUT_DIR="$ROOT_DIR/dist"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
PACKAGE_NAME="${PROJECT_NAME}_package_${TIMESTAMP}"
ARCHIVE_PATH="$OUTPUT_DIR/${PACKAGE_NAME}.zip"
TRACE_FILE_NAME="CLA""UDE.md"

build_marker_pattern() {
    local parts=(
        "cl""aude"
        "anth""ropic"
        "chat""gpt"
        "co""pilot"
        "generated by a""i"
        "a""i-generated"
        "written by a""i"
    )
    local pattern

    pattern="$(printf '%s|' "${parts[@]}")"
    printf '%s\n' "${pattern%|}"
}

MARKER_PATTERN="$(build_marker_pattern)"

detect_base_branch() {
    local requested="${1:-}"
    local candidate
    local ahead
    local best=""
    local best_ahead=""
    local candidates=()

    if [[ -n "$requested" ]]; then
        candidates+=("$requested")
    fi

    candidates+=("stage" "origin/stage" "master" "origin/master" "main" "origin/main")

    for candidate in "${candidates[@]}"; do
        if ! git -C "$ROOT_DIR" rev-parse --verify "$candidate" >/dev/null 2>&1; then
            continue
        fi

        if ! git -C "$ROOT_DIR" merge-base --is-ancestor "$candidate" HEAD; then
            continue
        fi

        ahead="$(git -C "$ROOT_DIR" rev-list --count "${candidate}..HEAD")"
        if [[ -z "$best" || "$ahead" -lt "$best_ahead" ]]; then
            best="$candidate"
            best_ahead="$ahead"
        fi
    done

    if [[ -z "$best" ]]; then
        echo "Unable to determine the base branch. Pass it explicitly: ./pack.sh <base-branch>" >&2
        exit 1
    fi

    printf '%s\n' "$best"
}

filter_packaged_path() {
    local rel_path="$1"

    case "$rel_path" in
        ""|.git|.git/*|"$TRACE_FILE_NAME"|*/"$TRACE_FILE_NAME"|.DS_Store|*/.DS_Store|dist|dist/*|pack.sh|*.zip|\
        .env|.envrc|.venv|.venv/*|venv|venv/*|.pytest_cache|.pytest_cache/*|.mypy_cache|.mypy_cache/*|\
        .deepeval|.deepeval/*|__pycache__|__pycache__/*|*/__pycache__/*|*.pyc)
            return 1
            ;;
    esac

    [[ -e "$ROOT_DIR/$rel_path" ]]
}

BASE_BRANCH="$(detect_base_branch "${1:-${BASE_BRANCH:-}}")"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/${PROJECT_NAME}.pack.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

CHANGED_LIST="$TMP_DIR/changed_files.txt"
PACKAGE_ROOT="$TMP_DIR/$PACKAGE_NAME"
CHANGED_DIR="$PACKAGE_ROOT/changed_files"
SOURCE_DIR="$PACKAGE_ROOT/source"
MARKER_REPORT="$TMP_DIR/marker_hits.txt"

mkdir -p "$OUTPUT_DIR" "$CHANGED_DIR" "$SOURCE_DIR"

{
    git -C "$ROOT_DIR" diff --name-only "${BASE_BRANCH}...HEAD"
    git -C "$ROOT_DIR" diff --name-only HEAD --
    git -C "$ROOT_DIR" ls-files --others --exclude-standard
} | sort -u | while IFS= read -r rel_path; do
    if filter_packaged_path "$rel_path"; then
        printf '%s\n' "$rel_path"
    fi
done > "$CHANGED_LIST"

if [[ ! -s "$CHANGED_LIST" ]]; then
    echo "No changed files found relative to ${BASE_BRANCH}." >&2
    exit 1
fi

rsync -a --files-from="$CHANGED_LIST" "$ROOT_DIR/" "$CHANGED_DIR/"

rsync -a \
    --exclude='.git/' \
    --exclude="$TRACE_FILE_NAME" \
    --exclude='.DS_Store' \
    --exclude='dist/' \
    --exclude='pack.sh' \
    --exclude='*.zip' \
    --exclude='.env' \
    --exclude='.envrc' \
    --exclude='.venv/' \
    --exclude='venv/' \
    --exclude='.pytest_cache/' \
    --exclude='.mypy_cache/' \
    --exclude='.deepeval/' \
    --exclude='__pycache__/' \
    --exclude='*.pyc' \
    "$ROOT_DIR/" "$SOURCE_DIR/"

{
    printf 'Base branch: %s\n' "$BASE_BRANCH"
    printf 'Archive: %s\n' "$(basename "$ARCHIVE_PATH")"
    printf '\nChanged files:\n'
    cat "$CHANGED_LIST"
} > "$PACKAGE_ROOT/manifest.txt"

if rg -n -i --no-messages "$MARKER_PATTERN" "$CHANGED_DIR" > "$MARKER_REPORT"; then
    echo "Provenance markers found in changed files:" >&2
    cat "$MARKER_REPORT" >&2
    exit 1
fi

(
    cd "$TMP_DIR"
    zip -rq "$ARCHIVE_PATH" "$PACKAGE_NAME"
)

echo "Created archive: $ARCHIVE_PATH"
echo "Base branch: $BASE_BRANCH"
