from src.utils.load_dataset_coolprompt import (
    squad_v2,
    squad_v2_preproc,
    gsm8k,
    gsm8k_preproc,
    common_gen,
    common_gen_preproc,
    ag_news,
    ag_news_preproc,
    xsum,
    xsum_preproc,
    sst2,
    sst2_preproc,
)


config_dict = {
    "sst2": {
        "start_prompt": "Please perform a sentiment classification task",
        "task": "classification",
        "metric": "f1",
        "preproc": sst2_preproc,
        "data": sst2,
        "test_name": "test",
        "problem_description": "sentiment classification",
    },
    "squad_v2": {
        "start_prompt": "Given a context answer on the question.",
        "task": "generation",
        "metric": "bertscore",
        "preproc": squad_v2_preproc,
        "data": squad_v2,
        "test_name": "validation",
        "problem_description": "question answering",
    },
    "gsm8k": {
        "start_prompt": "Given a context answer on the question.",
        "task": "generation",
        "metric": "em",
        "preproc": gsm8k_preproc,
        "data": gsm8k,
        "test_name": "test",
        "problem_description": "math solving",
    },
    "common_gen": {
        "start_prompt": "Create a short sentence using words in list.",
        "task": "generation",
        "metric": "bertscore",
        "preproc": common_gen_preproc,
        "data": common_gen,
        "test_name": "validation",
        "problem_description": "create a sentence",
    },
    "ag_news": {
        "start_prompt": "Classify news and provide number of topic from dict {{World: 0, Sports: 1, Business: 2, Sci/Tech: 3}}",
        "task": "classification",
        "metric": "f1",
        "preproc": ag_news_preproc,
        "data": ag_news,
        "test_name": "test",
        "problem_description": "classification",
    },
    "xsum": {
        "start_prompt": "Summarize the sentence.",
        "task": "generation",
        "metric": "bertscore",
        "preproc": xsum_preproc,
        "data": xsum,
        "test_name": "validation",
        "problem_description": "Summarization",
    },
}
