from pydantic import BaseModel, Field


class TextualGradientResponse(BaseModel):
    """Response schema for textual-gradient feedback generation."""

    feedback: str = Field(
        description=(
            "Detailed feedback on how the given prompt can be improved "
            "to achieve the best quality answer on the given problem "
            "description and not to repeat the same mistakes observed "
            "in the provided failed examples."
        )
    )


class ShortTermHintResponse(BaseModel):
    """Response schema for RE-GPS short-term reflection hints."""

    hint: str = Field(
        description=(
            "One new hint for designing a better prompt, derived from "
            "the two provided prompt versions (worse and better) and "
            "their respective improvement feedbacks. For example, the "
            "hint can recommend a word replacement, an active/positive "
            "voice conversion, adding a word or deleting a word."
        )
    )


class MutatedPromptResponse(BaseModel):
    """Response schema for RE-GPS elitist mutation prompts."""

    prompt: str = Field(
        description=(
            "A mutated prompt derived from the elitist prompt. The main "
            "priority is the provided prior (long-term) reflection, which "
            "accumulates essential information about correct prompt "
            "structure and other prompt features; the improvement "
            "feedback generated by the expert for the elitist prompt is "
            "also taken into account."
        )
    )
