# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - 'test_v*.*.*'

permissions:
  contents: read

jobs:
# Builds the pythond distribution (wheel and source tarball)
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checkout the code
    - name: Set up Python
      uses: actions/setup-python@v5 # Set up the Python environment
      with:
        python-version: "3.x"
    - name: Install pypa/build # Install the build tool
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build # Build the package
    - name: Store the distribution packages # Temporarily store the build artifacts in the dist directory under the name python-package-distributions
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  testpypi-publish:
    name: Publish to TestPyPI 🐍📦
    needs:
      - build # Start the job only if the build job has completed
    runs-on: ubuntu-latest
    
    environment:
      name: testpypi # Enter the environment name set in the Publisher
      url: https://test.pypi.org/p/coolprompt # Project URL
    
    permissions:
      id-token: write  # Grant Publishing permissions
    
    if: startsWith(github.ref, 'refs/tags/test_v') # Conditional check for TestPyPI publishing
    
    steps:
      - name: Download all the dists # Download the build artifacts that were saved earlier
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI # Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/